app/Http/routes.php
<?php

Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
	Route::get('login',		'AuthController@getLogin');
    Route::post('login',	'AuthController@postLogin');
    Route::get('logout',	'AuthController@getLogout');
});


Route::group(['middleware' => 'auth', 'namespace' => 'Admin'], function () {
	Route::get('/', 						'ContactsController@index');

	Route::get('/statistiques', 			'DashboardController@index');
	Route::get('/home', 					'DashboardController@index');

	Route::any('contacts/search', 			'ContactsController@index');
	Route::any('statistiques/search', 		'DashboardController@index');
	Route::any('statistiques/dons/search', 	'StatsdonsController@index');

	Route::resource('contacts', 			'ContactsController', ['except' => ['edit']]);
	Route::get('contacts/invite/{id}', 		'ContactsController@invite');
	Route::get('contacts/confirm/{id}', 	'ContactsController@confirm');

	Route::resource('evenements', 			'EvenementsController', ['except' => ['edit']]);
	Route::get('evenements/invite/{id}', 	'EvenementsController@invite');

	Route::resource('administrators', 		'AdministratorsController', ['except' => ['edit']]);


	Route::group(['namespace' => 'Contacts'], function () {
		Route::resource('contacts.participations', 'ParticipationsController', ['except' => ['index', 'edit']]);
		Route::resource('contacts.dons', 'DonsController', ['except' => ['index', 'show', 'update', 'edit']]);
	});

});

app/Don.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Don extends Model
{
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [ 'contact_id', 'amount', 'date_don', 'payment', 'marketing' ];


	/**
     * The attributes that should be casted to native types.
     *
     * @type array
     */
    protected $dates = [
        'date_don',
        'created_at', 
        'updated_at',
    ];
	

	/***** lists *****/
	public function getPaymentTypes() 
	{
		return [
			'CB'	=> 'CB', 
			'Chèque'		=> 'Chèque', 
			'Virement'	=> 'Virement', 
			'Espèces'	=> 'Espèces', 
			'Autres'	=> 'Autres', 
		];
	}

	public function getMarketingTypes() 
	{
		return [
			'Site internet' 		=> 'Site internet', 
			'Gala' 			=> 'Gala', 
			'Evènement' 	=> 'Evènement', 
			'Prospection' 	=> 'Prospection', 
			'Autres' 		=> 'Autres', 
		];
	}


	// belongs to

	/**
     * Get the participations's contact.
     */
	public function contact() 
	{
		return $this->belongsTo('App\Contact');
	}
	

	/***** scopes *****/
	public function scopeBetweenDate($query, $dates = []) 
	{
		if( ! isset($dates['min']) || strlen($dates['min']) == 0 &&
            ! isset($dates['max']) || strlen($dates['max']) == 0) {
            return $query;
        }

        $startDate = Carbon::createFromFormat('d/m/Y', $dates['min']);
        $endDate = Carbon::createFromFormat('d/m/Y', $dates['max']);

		return $query->whereBetween('date_don', [$startDate, $endDate]);;
	}

	public function scopeBetweenDateOrder($query, $direction)
	{
		return $query->orderBy('date_don', $direction);
	}


	/***** mutators *****/
    public function setDateDonAttribute($value)
    {
        $this->attributes['date_don'] = strlen($value) > 0 ? \Carbon\Carbon::createFromFormat('d/m/Y', $value) : \Carbon\Carbon::now();
    }

    public function getFormattedDateDonAttribute()
    {
    	return $this->date_don->format('d/m/Y');
    }

    public function getFormattedAmountAttribute() 
    {
    	return $this->amount . ' €';
    }

    public function getSearchFieldset($key = null) 
    {
        $fieldset =  [
            'contact_id'     => [
                'type'  => 'equal',
                'label' => 'Contact',
                'options'	=> Contact::getList(true),
                'value' => null,
            ],
            'scope.betweenDate' => [
                'type'  => 'between-dates',
                'label' => 'Date du don',
                'value' => [
                	'min' => null,
					'max' => null,
                ],
            ],
        ];

        if (is_string($key)) {
            return array_key_exists($key, $fieldset) ? $fieldset[$key] : null;
        }
        if (is_array($key)) {
            return array_only($fieldset, $key);
        }

        return $fieldset;
    }

}

app/Http/Controllers/Admin/StatsdonsController.php
<?php

namespace App\Http\Controllers\Admin;

use DB;
use App\Don;
use App\Http\Controllers\AdminController;
use Illuminate\Database\Eloquent\Builder as QueryBuilder;
use Illuminate\Http\Request;
use \App\Helpers\Searchform;
use \App\Exports\Dons as ExportDons;

class StatsdonsController extends AdminController
{
	use \App\Helpers\Searchform;

	const MODEL = Don::class;

	protected $actionUrl 		= 'statistiques/dons/search';

	protected $searchForm = [];

	protected $submitbuttons = [
		'Rechercher' => [
			'name'		=> 'submit',
			'type' 		=> 'submit',
			'class'		=> 'btn btn-primary btn-fill',
		],
		'Exporter' => [
			'name'		=> 'export',
			'type' 		=> 'submit',
			'class'		=> 'btn btn-success btn-fill'
		],
	];

	protected function boot() {
		parent::boot();

		$this->searchForm = [

		];

		$this->setSubmitButtons( $this->submitbuttons );
	}

	public function index(Request $request) {
		$this->boot();

		return $this->handleRender($request);
    }

    private function handleRender(Request $request) {
    	$object = $this->getModelInstance();

        $query = $object->query();

        if (is_null($request->fields)) {
            $query->with($this->with);
        }

        $query = $this->handleFieldsParameters($query, $request);
        $query = $this->handleOrderByParameters($query, $request);
        $query = $this->handleSearchParameters($query, $request);


        if ( method_exists($object, 'getSearchFieldset')
            && is_callable([$object, 'getSearchFieldset']) )
        {
            $this->setDatas('searchForm', $this->buildSearchForm( $object->getSearchFieldset(), $request ));
        }
    	
    	if (isset($request->export)) {
        	$export = new ExportDons( $query->get() );
        	return $export->render();
        }

        $query = $this->handlePaginationParameters($query, $request);
    	$this->setDatas('datas', $query->items());
    	$this->setDatas('query', $query);
    	
		return $this->render();
    }

}

resources/views/admin/statsdons/index.blade.php
@extends('admin.layout')

@section('breadcrumb')
	<a class="navbar-brand" href="#">Statistiques des dons</a>
@endsection

@section('searchform')
	{!! $searchForm or '' !!}
@endsection

@section('content')

	<div class="col-md-12">

		@yield('searchform')

		<div class="card">
			<div class="header">
				<h4 class="title">Statistiques des dons</h4>
			</div>

			<div class="content table-responsive table-full-width">

				<table class="table table-hover table-striped table-hover table-condensed">
					<thead>
						<tr>
							<th>Date</th>
							<th>Contact</th>
							<th>Montant</th>
							<th>Moyen de paiement</th>
						</tr>
					</thead>
					@if (!empty($datas))
						<tbody>
							@foreach ($datas as $don)
								<tr>
									<td>{{ $don->formatted_date_don }}</td>
									<td>{{ $don->contact ? $don->contact->full_name : '' }}</td>
									<td>{{ $don->formatted_amount }}</td>
									<td>{{ $don->payment }}</td>
								</tr>
							@endforeach
						</tbody>
					@endif
				</table>

				@if ($query->lastPage() > 1)
                <ul class="pagination pull-right">
				    <li class="{{ ($query->currentPage() == 1) ? ' disabled' : '' }}">
				        <a href="{{ $query->url(1) }}"><i class="fa fa-chevron-left"></i></a>
				    </li>
	                @for ($i = $initial = max(1, $query->currentPage() - 5), $l = min($initial + 10, $query->lastPage()); $i <= $l; $i++)
	                	<li class="{{ ($query->currentPage() == $i) ? ' active' : '' }}">
				            <a href="{{ $query->url($i) }}">{{ $i }}</a>
				        </li>
					@endfor
					<li class="{{ ($query->currentPage() == $query->lastPage()) ? ' disabled' : '' }}">
				        <a href="{{ $query->url($query->currentPage()+1) }}" ><i class="fa fa-chevron-right"></i></a>
				    </li>
				</ul>
				@endif
				
			</div>
		</div>
		
	</div>

@endsection