app/Http/routes.php
<?php

Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
	Route::get('login',		'AuthController@getLogin');
    Route::post('login',	'AuthController@postLogin');
    Route::get('logout',	'AuthController@getLogout');
});


Route::group(['middleware' => 'auth', 'namespace' => 'Admin'], function () {
	Route::get('/', 						'ContactsController@index');

	Route::get('/statistiques', 			'DashboardController@index');
	Route::get('/home', 					'DashboardController@index');

	Route::any('contacts/search', 			'ContactsController@index');
	Route::any('statistiques/search', 		'DashboardController@index');
	Route::any('statistiques/dons/search', 	'StatsdonsController@index');

	Route::resource('contacts', 			'ContactsController', ['except' => ['edit']]);
	Route::get('contacts/invite/{id}', 		'ContactsController@invite');
	Route::get('contacts/confirm/{id}', 	'ContactsController@confirm');

	Route::resource('evenements', 			'EvenementsController', ['except' => ['edit']]);
	Route::get('evenements/invite/{id}', 	'EvenementsController@invite');

	Route::resource('administrators', 		'AdministratorsController', ['except' => ['edit']]);


	Route::group(['namespace' => 'Contacts'], function () {
		Route::resource('contacts.participations', 'ParticipationsController', ['except' => ['index', 'edit']]);
		Route::resource('contacts.dons', 'DonsController', ['except' => ['index', 'show', 'update', 'edit']]);
	});

});

app/Contact.php
<?php

namespace App;

use DB;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Contact extends Model
{

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = ['civility', 'gender', 'society', 'particule', 'firstname', 'lastname', 'email', 'profession', 'address_1', 'address_2', 'postcode', 'city', 'country', 'telephone_1', 'telephone_2', 'birthdate'];


    /**
     * The attributes that should be casted to native types.
     *
     * @type array
     */
    protected $dates = [
        'birthdate',
        'created_at', 
        'updated_at',
    ];


    /* boot method */
    // public function boot()
    // {

    // }


	/***** has_many *****/

    /**
     * Get all the contact participations.
     */
    public function participations()
    {
        return $this->hasMany('App\Participation');
    }

    public function lastParticipation() {
        return $this->hasOne('App\Participation')->orderBy('id', 'desc');
    }

    public function lastestParticipation() 
    {
        return $this->hasOne('App\Participation')->inLastGala();
    }

    /**
     * Get all the contact dons.
     */
    public function dons()
    {
        return $this->hasMany('App\Don');
    }


	/* Scope a query to only include or exclude affaire with en cours fournitures.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWasInLastGala($query)  
    {
        return $query->has('lastestParticipation');
    }

    public function scopeByEvent($query, $eventId) 
    {
        return $query->with(['participations', function($q) use($eventId) {
            $q->where('gala_id', $eventId);
        }]);
    }

    public function scopeByInviting($query, $value) 
    {
        return $query->whereHas('participations', function($q) use($value) {
            $q->depthLike('invite_de', (string)$value);
        });
    }

    public function scopeByRelance($query, $value) {
        return $query->whereHas('participations', function($q) use($value) {
            $q->depthLike('relance', (string)$value);
        });
    }

    public function scopeByCategory($query, $value) {
        return $query;
    }

    public function scopeByMot($query, $value) {
        return $query->whereHas('participations', function($q) use($value) {
            $q->depthLike('mot_a_joindre', (string)$value);
        });
    }

    public function scopeByCarton($query, $value) {
        return $query->whereHas('participations', function($q) use($value) {
            $q->depthLike('carton_entreprise', (string)$value);
        });
    }

    public function scopeHavePaid($query, $value = 1) {
        return $query->with(['lastestParticipation' => function($q) use($value) {
            $q->where('paiement_place', ($value ? '>': '<='), 0);
        }]);
    }

    public function scopeHaveConfirmed($query, $value = 1) {
        return $query->with(['lastestParticipation' => function($q) use($value) {
            $q->where('confirmed', '=', $value);
        }]);
    }



	/***** mutators *****/
    public function setBirthdateAttribute($value)
    {
        $this->attributes['birthdate'] = strlen($value) > 0 ? \Carbon\Carbon::createFromFormat('d/m/Y', $value) : \Carbon\Carbon::now();
    }

    public function getFullNameAttribute()
    {
        return $this->civility . ' ' . ucfirst($this->lastname) . ' ' . $this->particule . ' ' .  ucfirst($this->firstname);
    }
    
    public function getTotalDonsAttribute()
    {
        if ($this->dons->isEmpty()) {
            return number_format(floatval(0), 2)." €";
        }

        return $this->dons->reduce(function ($total, $item) {
            return number_format(floatval(($total + $item->amount)), 2)." €";        
        });
    }

    public function getInviteDeAttribute() 
    {
        if (!is_null($this->lastestParticipation)) {
            return $this->lastestParticipation->invite_de;
        }

        return '---';
    }

    // invited mutators
    public function getIsInvitedInLastGalaAttribute() 
    {
        return !(is_null($this->lastestParticipation) || !$this->lastestParticipation->invited);
    }
    
    public function getInvitedInLastGalaAttribute() 
    {
        return $this->is_invited_in_last_gala ? 'Oui' : 'Non';
    }

    public function getCartonEntrepriseAttribute() 
    {
        return $this->lastestParticipation->carton_entreprise ? 'Oui' : 'Non';
    }

    public function getMotAJoindreAttribute() 
    {
        return !is_null($this->lastestParticipation->mot_a_joindre) ? $this->lastestParticipation->mot_a_joindre : '';
    }

    public function getCategoryAttribute() 
    {
        return ucfirst($this->lastestParticipation->category);
    }

    public function getPaiementPlaceAttribute() 
    {
        return $this->lastestParticipation->paiement_place ? 'Oui' : 'Non';
    }

    public function getInvitedBtnAttribute() 
    {
        if (is_null($this->lastestParticipation)) {
            return 'Non';
        }

        $url    = url('contacts/invite/'.$this->id);
        $class  = ($this->is_invited_in_last_gala) ? 'btn-success' : 'btn-danger';

        return '<a href="' . $url . '" class="btn btn-xs ' . $class . ' btn-fill">' . $this->invited_in_last_gala . '</a>';
    }

    // confirmed mutators
    public function getIsConfirmedInLastGalaAttribute() 
    {
        return !(is_null($this->lastestParticipation) || !$this->lastestParticipation->confirmed);
    }

    public function getConfirmedInLastGalaAttribute() 
    {
        return $this->is_confirmed_in_last_gala ? 'Oui' : 'Non';
    }

    public function getConfirmedBtnAttribute() 
    {
        if (is_null($this->lastestParticipation)) {
            return 'Non';
        }

        $url    = url('contacts/confirm/'.$this->id);
        $class  = ($this->is_confirmed_in_last_gala) ? 'btn-success' : 'btn-danger';

        return '<a href="' . $url . '" class="btn btn-xs ' . $class . ' btn-fill">' . $this->confirmed_in_last_gala . '</a>';
    }


    public function getFullAddressAttribute() {
        return $this->address_1 .' '. $this->address_2;
    }

    public function getFreeCivilityAttribute() {
        if(!in_array($this->civility, $this->getCivilityTypes())) {
            return $this->civility;
        }
        return "";
    }

    /***** lists *****/
	public function getCivilityTypes() 
	{
		return [
			'' 		=> '---',
			'Madame' 	=> 'Madame',
			'Mademoiselle' 	=> 'Mademoiselle',
            'Monsieur'    => 'Monsieur',
            'Monsieur et Madame'    => 'Monsieur et Madame',
            'Docteur'    => 'Docteur',
            'Madame le Docteur'    => 'Madame le Docteur',
            'Le Docteur et Madame'    => 'Le Docteur et Madame',
            'Madame le Professeur'    => 'Madame le Professeur',
            'Le Professeur et Madame'    => 'Le Professeur et Madame',
            'Le Comte et la Comtesse'    => 'Le Comte et la Comtesse',
            'Le Baron et la Baronne'    => 'Le Baron et la Baronne',
		];
	}

	public function getGenderTypes() 
	{
		return [
			'' 		=> '---',
			'M'		=> 'Homme',
			'F'		=> 'Femme',
		];
	}

    public static function getList($emptyLine = false) {
        $list = self::all()->pluck('full_name', 'id')->toArray();

        return $emptyLine ? ['' => 'Tous les contacts'] + $list : $list;
    }


    /***** form helper *****/
    public function getSearchFieldset($key = null) {
        $fieldset =  [
            'firstname'     => [
                'type'  => 'like',
                'label' => 'Nom',
                'value' => null,
            ],
            'postcode'      => [
                'type'  => 'like',
                'label' => 'Code postal',
                'value' => null,
            ],
        ];

        if (is_string($key)) {
            return array_key_exists($key, $fieldset) ? $fieldset[$key] : null;
        }
        if (is_array($key)) {
            return array_only($fieldset, $key);
        }

        return $fieldset;
    }


    /***** requesting functions *****/
    public static function getResults( Request $request) {

        $searchTerms = $request->search;

        if (is_null($searchTerms)) {
            return self::with(['participations', 'dons']);
        }

        $subquery = DB::table('participations')->select('contact_id');
        foreach ($searchTerms as $key => $value) {
            if ($key == 'gala_id' && isset($value['equal']) && $value['equal'] > 0) {
                $subquery->where($key, '=', $value['equal']);
            } elseif ($key != 'gala_id' && isset($value['equal']) && strlen($value['equal']) > 0) {
                $subquery->where($key, '=', $value['equal']);
            } elseif (isset($value['like']) && strlen($value['like']) > 0) {
                $subquery->where($key, 'like', '%'.$value['like'].'%');
            } elseif (isset($value['bool']) && !is_null($value['bool']) && $value['bool'] != '') {
                if ($key == 'paiement_place') {
                    $subquery->where($key, ($value['bool'] ? '>' : '='), 0);
                } else {
                    $subquery->where($key, $value['bool']);
                }
            }
        }

        $list_ids = array();

        foreach ($subquery->get() as $participant) {
            $list_ids[] = $participant->contact_id;
        }

        return self::with(['participations', 'dons'])->whereIn('id', $list_ids);          
    }
}

app/Don.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Don extends Model
{
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [ 'contact_id', 'amount', 'date_don', 'payment', 'marketing' ];


	/**
     * The attributes that should be casted to native types.
     *
     * @type array
     */
    protected $dates = [
        'date_don',
        'created_at', 
        'updated_at',
    ];
	

	/***** lists *****/
	public function getPaymentTypes() 
	{
		return [
			'CB'	=> 'CB', 
			'Chèque'		=> 'Chèque', 
			'Virement'	=> 'Virement', 
			'Espèces'	=> 'Espèces', 
			'Autres'	=> 'Autres', 
		];
	}

	public function getMarketingTypes() 
	{
		return [
			'Site internet' 		=> 'Site internet', 
			'Gala' 			=> 'Gala', 
			'Evènement' 	=> 'Evènement', 
			'Prospection' 	=> 'Prospection', 
			'Autres' 		=> 'Autres', 
		];
	}


	// belongs to

	/**
     * Get the participations's contact.
     */
	public function contact() 
	{
		return $this->belongsTo('App\Contact');
	}
	

	/***** scopes *****/
	public function scopeBetweenDate($query, $dates = []) 
	{
		if( ! isset($dates['min']) || strlen($dates['min']) == 0 &&
            ! isset($dates['max']) || strlen($dates['max']) == 0) {
            return $query;
        }

        $startDate = Carbon::createFromFormat('d/m/Y', $dates['min']);
        $endDate = Carbon::createFromFormat('d/m/Y', $dates['max']);

		return $query->whereBetween('date_don', [$startDate, $endDate]);;
	}

	public function scopeBetweenDateOrder($query, $direction)
	{
		return $query->orderBy('date_don', $direction);
	}


	/***** mutators *****/
    public function setDateDonAttribute($value)
    {
        $this->attributes['date_don'] = strlen($value) > 0 ? \Carbon\Carbon::createFromFormat('d/m/Y', $value) : \Carbon\Carbon::now();
    }

    public function getFormattedDateDonAttribute()
    {
    	return $this->date_don->format('d/m/Y');
    }

    public function getFormattedAmountAttribute() 
    {
    	return $this->amount . ' €';
    }

    public function getSearchFieldset($key = null) 
    {
        $fieldset =  [
            'contact_id'     => [
                'type'  => 'equal',
                'label' => 'Contact',
                'options'	=> Contact::getList(true),
                'value' => null,
            ],
            'scope.betweenDate' => [
                'type'  => 'between-dates',
                'label' => 'Date du don',
                'value' => [
                	'min' => null,
					'max' => null,
                ],
            ],
        ];

        if (is_string($key)) {
            return array_key_exists($key, $fieldset) ? $fieldset[$key] : null;
        }
        if (is_array($key)) {
            return array_only($fieldset, $key);
        }

        return $fieldset;
    }

}

app/Http/Controllers/Admin/Contacts/DonsController.php
<?php

namespace App\Http\Controllers\Admin\Contacts;

use App\Don;
use App\Http\Controllers\AdminController;
use Illuminate\Database\Eloquent\Builder as QueryBuilder;
use Illuminate\Http\Request;

class DonsController extends AdminController
{
    const MODEL = Don::class;
    protected $with = [];

    protected $name = 'dons';

    protected $validation = [
		'amount'		=> 'numeric',
		'date_don'		=> 'required|date_format:d/m/Y',
		'payment'		=> 'required|string',
		'marketing'		=> 'required|string',
    ];

     /**
     * Override pour ajout des valeurs par défaut.
     */
    public function create()
    {
    	$this->boot();

        $object = $this->getModelInstance();

        $object->contact_id = (int)Request()->segment(2);

        $this->setDatas('model', $object);

        return $this->render();
    }

    /**
     * Override pour enregistrement des valeurs par défaut.
     */
    public function store(Request $request)
    {
        $this->boot();

        $model = static::MODEL;

        $this->validate($request, $this->validation, $this->messages, $this->attributes);

        $attributes = $request->only(array_keys($this->validation));
        $attributes['contact_id'] = (int)Request()->segment(2);
        
        $object = $model::create($attributes);
        $object->load($this->with);

        if (!is_null($object)) {
            return redirect()->route( 'contacts.show', $object->contact_id )->with('success', 'Modification enregistrée');
        }

        return $object;
    }

    /**
     * Override pour suppression
     */
    public function destroy($id)
    {
        $this->boot();

        $model = static::MODEL;

        $requestId = (int)Request()->segment(4);

        $model::where('contact_id', '=', $id)->where('id', '=', $requestId)->firstOrFail()->delete();

        return redirect()->route( 'contacts.show', $id )->with('success', 'Element supprimé');
    }
}

resources/views/admin/contacts/index.blade.php
@extends('admin.layout')

@section('breadcrumb')
	<a class="navbar-brand" href="#">Contacts</a>
@endsection

@section('searchform')
	{!! $searchForm or '' !!}
@endsection

@section('content')
	
	<div class="col-md-12">
        
        @yield('searchform')
        
        <div class="card">
            <div class="header">
                <h4 class="title">Liste des contacts</h4>
                <div class="clearfix">
                	<a href="{{ url('contacts/create') }}" class="btn btn-success btn-fill">Ajouter un contact</a>
                </div>
            </div>

            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped table-hover table-condensed">
                    <thead>
                        <tr>
	                    	<th>Nom</th>
	                    	<th>Prénom</th>
	                    	<th>Code postal</th>
	                    	<th>Ville</th>
	                    	<th>Invité de</th>
	                    	<th>Invitation envoyée</th>
	                    	<th>Participation confirmée</th>
	                    	<th class="actions">Actions</th>
	                    </tr>
	                </thead>
	                @if (!empty($datas))
	                    <tbody>

	                    	@foreach ($datas as $contact)
		                        <tr>
		                        	<td>{{ $contact->firstname }}</td>
		                        	<td>{{ $contact->lastname }}</td>
		                        	<td>{{ $contact->postcode }}</td>
		                        	<td>{{ $contact->city }}</td>
		                        	<td>{{ $contact->invite_de }}</td>
		                        	<td>{!! $contact->invited_btn !!}</td>
		                        	<td>{!! $contact->confirmed_btn !!}</td>
		                        	<td class="actions">
		                        		<a href="{{ url('contacts/'.$contact->id) }}" class="btn btn-xs btn-info btn-fill pull-right">
		                        			Voir
		                        		</a>
		                        		{!! Form::open(['method' => 'delete', 'route' => ['contacts.destroy', $contact->id], 'class' => 'pull-right', 'onsubmit' => 'return confirm(\'Supprimer définitivement la ligne ?\')']) !!}
		                        			{!! Form::submit('Supprimer', ['class' => 'btn btn-xs btn-danger btn-fill']) !!}
		                        		{!! Form::close() !!}
		                        	</td>
		                        </tr>
	                        @endforeach
	                    </tbody>
					@endif
                </table>

                @if ($query->lastPage() > 1)
                <ul class="pagination pull-right">
				    <li class="{{ ($query->currentPage() == 1) ? ' disabled' : '' }}">
				        <a href="{{ $query->url(1) }}"><i class="fa fa-chevron-left"></i></a>
				    </li>
	                @for ($i = $initial = max(1, $query->currentPage() - 5), $l = min($initial + 10, $query->lastPage()); $i <= $l; $i++)
	                	<li class="{{ ($query->currentPage() == $i) ? ' active' : '' }}">
				            <a href="{{ $query->url($i) }}">{{ $i }}</a>
				        </li>
					@endfor
					<li class="{{ ($query->currentPage() == $query->lastPage()) ? ' disabled' : '' }}">
				        <a href="{{ $query->url($query->currentPage()+1) }}" ><i class="fa fa-chevron-right"></i></a>
				    </li>
				</ul>
				@endif

            </div>
        </div>
    </div>

@endsection

resources/views/admin/contacts/show.blade.php
@extends('admin.layout')

@section('breadcrumb')
	<a class="navbar-brand" href="{{ url('contacts') }}">Contacts</a>
	<span class="navbar-brand"> | </span>
	<a class="navbar-brand" href="#">Editer un contact</a>
	<span class="navbar-brand"> | </span>
	<a class="navbar-brand" href="#">{{ $model->full_name }}</a>
@endsection

@section('content')

	<div class="col-md-12">

		<div class="card">
	        <div class="header">
	            <h4 class="title">Modifier un contact</h4>
	        </div>
	        <div class="content contact">
	        	{!! Form::model($model, ['method' => 'put', 'route' => ['contacts.update', $model->id], 'class' => 'clearfix']) !!}  

	        		<div class="col-md-6">
	        			<div class="header">
	        				<legend class="title">Contact</legend>
		        		</div>

		        		<div class="content">
		        			<div class="row">
		        				<div class="form-group">
							        {!! Form::label('civility', 'Civilité', ['class' => 'col-md-3 control-label text-right']) !!}
		        					<div class="col-md-9">
					        			{!! Form::select('civility', $model->getCivilityTypes(), null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
		        			</div>
		        			<div class="row free_civility">
		        				<div class="form-group">
							        {!! Form::label('free_civility', 'Autre civilité', ['class' => 'col-md-3 control-label text-right']) !!}
		        					<div class="col-md-9">
					        			{!! Form::text('free_civility', null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
		        			</div>
		        			<div class="row">
		                		<div class="form-group">
							        {!! Form::label('particule', 'Particule', ['class' => 'col-md-3 control-label text-right']) !!}
							        <div class="col-md-9">
								        {!! Form::text('particule', null, ['class' => 'form-control']) !!}
							        </div>
							    </div>
					        </div>
					        <div class="row">
		                		<div class="form-group">
							        {!! Form::label('firstname', 'Nom', ['class' => 'col-md-3 control-label text-right']) !!}
							        <div class="col-md-9">
								        {!! Form::text('firstname', null, ['class' => 'form-control']) !!}
							        </div>
							    </div>
					        </div>
					        <div class="row">
		                		<div class="form-group">
							        {!! Form::label('lastname', 'Prénom', ['class' => 'col-md-3 control-label text-right']) !!}
							        <div class="col-md-9">
								        {!! Form::text('lastname', null, ['class' => 'form-control']) !!}
							        </div>
							    </div>
					        </div>
					        <div class="row">
		                		<div class="form-group">
							        {!! Form::label('email', 'Adresse E-mail', ['class' => 'col-md-3 control-label text-right']) !!}
							        <div class="col-md-9">
							        	{!! Form::text('email', null, ['class' => 'form-control']) !!}
							    	</div>
							    </div>
					        </div>
					        <div class="row">
		                		<div class="form-group">
		                			{!! Form::label('telephone_1', 'Tél. principal', ['class' => 'col-md-3 control-label text-right']) !!}
		                			<div class="col-md-9">
							        	{!! Form::text('telephone_1', null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
						    </div>
						    <div class="row">
		                		<div class="form-group">
		                			{!! Form::label('telephone_2', 'Tél. secondaire', ['class' => 'col-md-3 control-label text-right']) !!}
		                			<div class="col-md-9">
							        	{!! Form::text('telephone_2', null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
						    </div>
						    <div class="row">
		                		<div class="form-group">
							        {!! Form::label('gender', 'Sexe', ['class' => 'col-md-3 control-label text-right']) !!}
							        <div class="col-md-9">
					        			{!! Form::select('gender', $model->getGenderTypes(), null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
						    </div>
						    <div class="row">
		                		<div class="form-group">
							        {!! Form::label('birthdate', 'Date de naissance', ['class' => 'col-md-3 control-label text-right']) !!}
							        <div class="col-md-9">
							        	{!! Form::text('birthdate', $model->birthdate ? $model->birthdate->format('d/m/Y') : '', ['class' => 'form-control datepicker']) !!}
							    	</div>
							    </div>
					        </div>
					        <div class="row">
		                		<div class="form-group">
							        {!! Form::label('society', 'Société', ['class' => 'col-md-3 control-label text-right']) !!}
							        <div class="col-md-9">
								        {!! Form::text('society', null, ['class' => 'form-control']) !!}
								    </div>
							    </div>
					        </div>
					        <div class="row">
		                		<div class="form-group">
							        {!! Form::label('profession', 'Profession', ['class' => 'col-md-3 control-label text-right']) !!}
							        <div class="col-md-9">
								        {!! Form::text('profession', null, ['class' => 'form-control']) !!}
								    </div>
							    </div>
					        </div>
	        			</div>

	        		</div>

	        		<div class="col-md-6">
        				<div class="header">
        					<legend class="title">Adresse</legend>
	        			</div>

	        			<div class="content">
				        	<div class="row">
		                		<div class="form-group">
		                			{!! Form::label('address_1', 'Adresse ligne 1', ['class' => 'col-md-3 control-label text-right']) !!}
		                			<div class="col-md-9">
								        {!! Form::text('address_1', null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
						    </div>
				        	<div class="row">
		                		<div class="form-group">
		                			{!! Form::label('address_2', 'Adresse ligne 2', ['class' => 'col-md-3 control-label text-right']) !!}
		                			<div class="col-md-9">
								        {!! Form::text('address_2', null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
						    </div>
				        	<div class="row">
		                		<div class="form-group">
		                			{!! Form::label('postcode', 'Code postal', ['class' => 'col-md-3 control-label text-right']) !!}
		                			<div class="col-md-9">
								        {!! Form::text('postcode', null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
						    </div>
						    <div class="row">
		                		<div class="form-group">
		                			{!! Form::label('city', 'Ville', ['class' => 'col-md-3 control-label text-right']) !!}
		                			<div class="col-md-9">
								        {!! Form::text('city', null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
						    </div>
						    <div class="row">
		                		<div class="form-group">
		                			{!! Form::label('country', 'Pays', ['class' => 'col-md-3 control-label text-right']) !!}
		                			<div class="col-md-9">
								        {!! Form::text('country', null, ['class' => 'form-control']) !!}
						    		</div>
						    	</div>
						    </div>
	        			</div>

	        		</div>

		        	<div class="clearfix"></div>
		        	{!! Form::submit('Enregistrer', ['class' => 'btn btn-info btn-fill pull-right']) !!}

	        	{!! Form::close() !!}
	        </div>
	    </div>

	    <div class="card">
	    	<div class="header">
                <h4 class="title">Présent(e) aux événements suivants</h4>
                <div class="clearfix">
                	<a href="{{ route('contacts.participations.create', $model->id) }}" class="btn btn-success btn-fill">Ajouter une participation</a>
                </div>
            </div>
            <div class="content table-responsive table-full-width">

            	<table class="table table-hover table-striped table-hover table-condensed">
            		<thead>
                        <tr>
	                    	<th>Désignation</th>
	                    	<th>Date</th>
	                    	<th class="actions">Actions</th>
	                    </tr>
	                </thead>
	                @if (!empty($model->participations))
	                    <tbody>
	                    	@foreach ($model->participations as $participation)
		                    	<tr>
		                    		<td>{{ $participation->gala->name }}</td>
		                    		<td>{{ $participation->gala->date ? $participation->gala->date->format('d/m/Y') : '' }}</td>
		                    		<td class="actions">
		                    			<a href="{{ route('contacts.participations.show', [$participation->contact_id, $participation->id]) }}" class="btn btn-xs btn-info btn-fill pull-right">
		                        			Voir
		                        		</a>
		                        		{!! Form::open(['method' => 'delete', 'route' => ['contacts.participations.destroy', $participation->contact_id, $participation->id], 'class' => 'pull-right', 'onsubmit' => 'return confirm(\'Supprimer définitivement la ligne ?\')']) !!}
		                        			{!! Form::submit('Supprimer', ['class' => 'btn btn-xs btn-danger btn-fill']) !!}
		                        		{!! Form::close() !!}
		                    		</td>
		                    	</tr>
	                    	@endforeach
	                    </tbody>
                    @endif
            	</table>

    		</div>
    	</div>

    	<div class="card">
	    	<div class="header">
                <h4 class="title">Dons <em>(Total : {{ $model->total_dons }}€)</em></h4>
                <div class="clearfix">
                	<a href="{{ route('contacts.dons.create', $model->id) }}" class="btn btn-success btn-fill">Ajouter un don</a>
                </div>
            </div>
            <div class="content table-responsive table-full-width">

            	<table class="table table-hover table-striped table-hover table-condensed">
            		<thead>
                        <tr>
	                    	<th>Montant</th>
	                    	<th>Date</th>
	                    	<th>Moyen de paiement</th>
	                    	<th class="actions">Actions</th>
	                    </tr>
	                </thead>
	                @if (!empty($model->dons))
	                    <tbody>
	                    	@foreach ($model->dons as $don)
		                    	<tr>
		                    		<td>{{ $don->amount }} €</td>
		                    		<td>{{ $don->formatted_date_don }}</td>
		                    		<td>{{ $don->payment }}</td>
		                    		<td class="actions">
		                    			{!! Form::open(['method' => 'delete', 'route' => ['contacts.dons.destroy', $don->contact_id, $don->id], 'class' => 'pull-right', 'onsubmit' => 'return confirm(\'Supprimer définitivement la ligne ?\')']) !!}
		                        			{!! Form::submit('Supprimer', ['class' => 'btn btn-xs btn-danger btn-fill']) !!}
		                        		{!! Form::close() !!}
		                    		</td>
		                    	</tr>
	                    	@endforeach
	                    </tbody>
                    @endif
            	</table>

    		</div>
    	</div>

    </div>

@endsection